In [1]:
#numpy into
import numpy
n = numpy.arange(27)

In [2]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [6]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
n.reshape(2,10)

ValueError: cannot reshape array of size 27 into shape (2,10)

In [9]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [21]:
m = numpy.asarray([[123,12,123,12,33],[],[],[]], dtype=object)

In [18]:
m

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [22]:
m.reshape(2,2)

array([[list([123, 12, 123, 12, 33]), list([])],
       [list([]), list([])]], dtype=object)

In [23]:
##Convert images to numpy arrays
import cv2

In [28]:
im_sg = cv2.imread('smallgray.png',0)
#0 for grescale, 1 for BGR(not RGB)

In [29]:
im_sg

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [31]:
im_sg = cv2.imread('smallgray.png',1)
im_sg

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [33]:
cv2.imwrite("newsmallgrey.png", im_sg)
#check the folder there will new image

True

In [3]:
import numpy
import cv2
#splicing numpy arrays

In [4]:
im_sg = cv2.imread('smallgray.png',0)
print(im_sg)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [5]:
#splicing rows
im_sg[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [6]:
#splicing rows and colums
im_sg[0:2,0:2]

array([[187, 158],
       [198, 125]], dtype=uint8)

In [7]:
im_sg[0,0]

187

In [8]:
for i in im_sg:
    print(i)
#print rows

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [9]:
for i in im_sg.T:
    print(i)
#print colums

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [10]:
for i in im_sg.flat:
    print(i)
#print each one

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [11]:
#stacking arrays
ims=numpy.hstack(im_sg,im_sg)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [12]:
ims=numpy.hstack((im_sg,im_sg))
print(ims)
#stack horizontally(use tupple)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [14]:
ims=numpy.vstack((im_sg,im_sg))
print(ims)
#stack vertically
#all stakcing nneds to be same dimensions

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [18]:
ims=numpy.hstack((im_sg,im_sg))
print(ims)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [21]:
lst=numpy.hsplit(ims,2)
print(lst)
#split colums

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]


In [22]:
lst=numpy.vsplit(ims,3)
print(lst)
#split rows

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8), array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147]], dtype=uint8), array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)]


In [23]:
type(lst)
#can access as normal list

list

In [24]:
lst[0]

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8)